// <auto-generated />
using System;
using System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MidStateShuttleService.Models;

#nullable disable

namespace MidStateShuttleService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319154157_RemovedDriverFromRoute")]
    partial class RemovedDriverFromRoute
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MidStateShuttleService.Models.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusId"));

                    b.Property<int>("BusNo")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("int");

                    b.HasKey("BusId");

                    b.HasIndex("DriverId");

                    b.ToTable("Bus", (string)null);
                });

            modelBuilder.Entity("MidStateShuttleService.Models.CheckIn", b =>
                {
                    b.Property<int>("CheckInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckInId"));

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DropOffLocationId")
                        .HasColumnType("int");

                    b.Property<bool>("FirstTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("CheckInId");

                    b.HasIndex("DropOffLocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("CheckIn", (string)null);
                });

            modelBuilder.Entity("MidStateShuttleService.Models.CommuncateModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DispatchMessageId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DropOffLocationID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PickUpLocationID")
                        .HasColumnType("int");

                    b.Property<int>("SelectedRouteDetail")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasAnnotation("ErrorMessage", "This field must not be more than 160 characters.");

                    b.HasKey("id");

                    b.HasIndex("DropOffLocationID");

                    b.HasIndex("PickUpLocationID");

                    b.ToTable("DispatchMessage", (string)null);
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasAnnotation("EmailAddress", "Invalid Email Address");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasAnnotation("RegularExpression", "^\\d{10,20}$");

                    b.HasKey("DriverId");

                    b.ToTable("Driver", (string)null);
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Anonymous");

                    b.Property<DateTime>("DateSubmitted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<bool>("DisplayTestimonial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("DisplayTestimonial");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("FeedbackId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasAnnotation("ErrorMessage", "Abbreviation must contain only characters and be exactly 3 characters long.")
                        .HasAnnotation("RegularExpression", "^[A-Za-z]{3,3}$");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasAnnotation("ErrorMessage", "Address must contain only characters and numbers, be at least 2 characters long, and not exceed 50 characters.")
                        .HasAnnotation("RegularExpression", "^[A-Za-z0-9\\s]{2,50}$");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("ErrorMessage", "City must contain only characters, be at least 2 characters long, and not exceed 50 characters.")
                        .HasAnnotation("RegularExpression", "^[A-Za-z\\s]{2,50}$");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("ErrorMessage", "Name must contain only characters, be at least 2 characters long, and not exceed 25 characters.")
                        .HasAnnotation("RegularExpression", "^[A-Za-z\\s]{2,25}$");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasDefaultValue("WI");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasAnnotation("ErrorMessage", "Zip code must contain only numbers, be at least 5 digits long, and not exceed 10 digits.")
                        .HasAnnotation("RegularExpression", "^[0-9]{5,10}$");

                    b.HasKey("LocationId");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Message", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MessageId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("contactInfo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasAnnotation("ErrorMessage", "This field must not be more than 160 characters.");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasAnnotation("ErrorMessage", "Must contain only characters and be at least 2 characters long")
                        .HasAnnotation("RegularExpression", "^[A-Za-z\\s]{2,}$");

                    b.Property<bool>("responseRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("id")
                        .HasName("PK_Message");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("MidStateShuttleService.Models.RegisterModel", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<bool>("AgreeTerms")
                        .HasColumnType("bit");

                    b.Property<int?>("DropOffLocationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("InsertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAdult")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFieldTrip")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInternalInquiry")
                        .HasColumnType("bit");

                    b.Property<int>("LengthOfRequest")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PickUpLocationID")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("customDate")
                        .HasColumnType("date");

                    b.Property<string>("customDropoffLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customPickupLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("customTime1")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("customTime2")
                        .HasColumnType("time");

                    b.Property<bool>("isCustom")
                        .HasColumnType("bit");

                    b.HasKey("RegistrationId");

                    b.HasIndex("DropOffLocationID");

                    b.HasIndex("PickUpLocationID");

                    b.HasIndex("UserId");

                    b.ToTable("Registration", (string)null);
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Routes", b =>
                {
                    b.Property<int>("RouteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteID"));

                    b.Property<string>("AdditionalDetails")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasAnnotation("ErrorMessage", "Additional details can only contain letters, numbers, and important special characters.")
                        .HasAnnotation("RegularExpression", "^[a-zA-Z0-9.,!?'\";:@#$%^&*()_+=\\-\\/]*$");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DropOffLocationID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("DropOffTime")
                        .HasColumnType("TIME")
                        .HasColumnName("DropOffTime")
                        .HasAnnotation("DataType", "Time")
                        .HasAnnotation("DisplayFormat", "{0:hh\\:mm tt}")
                        .HasAnnotation("ErrorMessage", "Please enter a valid time.")
                        .HasAnnotation("RegularExpression", "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$")
                        .HasAnnotation("SqlDbType", SqlDbType.Time);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PickUpLocationID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("PickUpTime")
                        .HasColumnType("TIME")
                        .HasColumnName("PickUpTime")
                        .HasAnnotation("DataType", "Time")
                        .HasAnnotation("ErrorMessage", "Please enter a valid time.")
                        .HasAnnotation("RegularExpression", "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$")
                        .HasAnnotation("SqlDbType", SqlDbType.Time);

                    b.HasKey("RouteID");

                    b.HasIndex(new[] { "DropOffLocationID" }, "IX_Route_DropOffLocationID");

                    b.HasIndex(new[] { "PickUpLocationID" }, "IX_Route_PickUpLocationID");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("MidStateShuttleService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureAdObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RequestDay", b =>
                {
                    b.Property<int>("RequestDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestDayId"));

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("WeekDay")
                        .HasColumnType("int");

                    b.HasKey("RequestDayId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("RequestDay");
                });

            modelBuilder.Entity("Ride", b =>
                {
                    b.Property<int>("RideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RideId"));

                    b.Property<int>("DropOffLocationID")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("DropOffTime")
                        .HasColumnType("time");

                    b.Property<int>("PickUpLocationID")
                        .HasColumnType("int");

                    b.Property<int>("RequestDayId")
                        .HasColumnType("int");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("RideId");

                    b.HasIndex("DropOffLocationID");

                    b.HasIndex("PickUpLocationID");

                    b.HasIndex("RequestDayId");

                    b.HasIndex("RouteId");

                    b.ToTable("Ride");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Bus", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.CheckIn", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Location", "DropOffLocation")
                        .WithMany()
                        .HasForeignKey("DropOffLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MidStateShuttleService.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DropOffLocation");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.CommuncateModel", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("DropOffLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MidStateShuttleService.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("PickUpLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MidStateShuttleService.Models.RegisterModel", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("DropOffLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Registration_DropOffLocation");

                    b.HasOne("MidStateShuttleService.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("PickUpLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Registration_PickUpLocation");

                    b.HasOne("MidStateShuttleService.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.Routes", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Location", "DropOffLocation")
                        .WithMany()
                        .HasForeignKey("DropOffLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MidStateShuttleService.Models.Location", "PickUpLocation")
                        .WithMany()
                        .HasForeignKey("PickUpLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DropOffLocation");

                    b.Navigation("PickUpLocation");
                });

            modelBuilder.Entity("RequestDay", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.RegisterModel", "Registration")
                        .WithMany("DaySchedules")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Ride", b =>
                {
                    b.HasOne("MidStateShuttleService.Models.Location", "DropOffLocation")
                        .WithMany()
                        .HasForeignKey("DropOffLocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MidStateShuttleService.Models.Location", "PickUpLocation")
                        .WithMany()
                        .HasForeignKey("PickUpLocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestDay", "RequestDay")
                        .WithMany("Rides")
                        .HasForeignKey("RequestDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MidStateShuttleService.Models.Routes", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId");

                    b.Navigation("DropOffLocation");

                    b.Navigation("PickUpLocation");

                    b.Navigation("RequestDay");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("MidStateShuttleService.Models.RegisterModel", b =>
                {
                    b.Navigation("DaySchedules");
                });

            modelBuilder.Entity("RequestDay", b =>
                {
                    b.Navigation("Rides");
                });
#pragma warning restore 612, 618
        }
    }
}
